include(CheckCXXCompilerFlag)

macro(UPDATE_CXX_COMPILER_FLAG target flag name)
    check_cxx_compiler_flag(${flag} COMPILER_SUPPORTS_${name}_FLAG)
    if(COMPILER_SUPPORTS_${name}_FLAG)
        add_definitions(${flag})
        #get_target_property(_FLAGS ${target} COMPILE_FLAGS)
        #if(${_FLAGS} STREQUAL "_FLAGS-NOTFOUND")
        #   set(_FLAGS "")
        #endif()
        #list(APPEND _FLAGS ${flag})
        #message("${_FLAGS}")
        #set_target_properties(${target} PROPERTIES COMPILE_FLAGS -DLOL)
    endif()
    set(${name} TRUE)
endmacro()
