if(WIN32)
    set(BUNDLE_NAME ${_name}.exe)
    set(BINDIR bin)
    set(BUNDLE_PATH "\${CMAKE_INSTALL_PREFIX}/${BINDIR}/${BUNDLE_NAME}")
    set(LIBDIR lib${LIB_SUFFIX})
    set(SHAREDIR share)
    set(PLUGINSDIR bin)
    set(IMPORTSDIR ${BINDIR})
    set(RLIBDIR ${BINDIR})
elseif(APPLE)
    set(BUNDLE_NAME ${_name}.app)
    set(BUNDLE_PATH "\${CMAKE_INSTALL_PREFIX}/${BUNDLE_NAME}")
    set(BINDIR ${BUNDLE_NAME}/Contents/MacOS)
    set(LIBDIR ${BINDIR})
    set(RLIBDIR ${BUNDLE_NAME}/Contents/Frameworks)
    set(SHAREDIR ${BUNDLE_NAME}/Contents/Resources)
    set(PLUGINSDIR ${BUNDLE_NAME}/Contents/PlugIns)
    set(IMPORTSDIR ${BINDIR})
else()
    set(BUNDLE_NAME ${_name})
    set(BINDIR bin)
    set(BUNDLE_PATH "\${CMAKE_INSTALL_PREFIX}/${BINDIR}/${BUNDLE_NAME}")
    set(LIBDIR lib${LIB_SUFFIX})
    set(RLIBDIR ${LIBDIR})
    set(SHAREDIR share/apps/${_name})
    set(PLUGINSDIR ${LIBDIR}/plugins/)
    set(IMPORTSDIR ${BINDIR}) #)${LIBDIR}/imports)
endif()

if(APPLE)
    set(DEPLOY_APP "${BUNDLE_NAME}")
else()
    set(DEPLOY_APP "bin/${BUNDLE_NAME}")
endif()
